# Generated by Django 4.2.16 on 2024-09-28 08:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان انگلیسی')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='mp4/')),
                ('hls_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک hls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات SEO')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال انتشار')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='آدرس قابل خواندن')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='categories.category')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'مدیریت ویدیو ها',
                'db_table': 'videos',
            },
        ),
    ]
