# Generated by Django 4.2.16 on 2024-10-01 06:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import libs.hash_video_covers


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_visibility_alter_category_image'),
        ('videos', '0002_video_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=libs.hash_video_covers.hashed_upload_path, verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='categories.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='نمایش در بالای صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی (با علامت , جدا کنید)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='mp4/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='فایل ویدیو'),
        ),
    ]
