# Generated by Django 4.2.16 on 2024-10-14 06:12

import django.core.validators
from django.db import migrations, models
import libs.hash_video_covers


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_cover_alter_video_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=libs.hash_video_covers.hashed_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
    ]
