# Generated by Django 4.2.16 on 2024-09-30 07:34

from django.db import migrations, models
import libs.hash_category_images


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=libs.hash_category_images.hashed_upload_path, verbose_name='کاور'),
        ),
    ]
